config/routes.rb
Oneweekpst::Application.routes.draw do
  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  get "test" => "pages#test"
  get "q1" => "pages#q1"
  get "q2" => "pages#q2"
  get "q3" => "pages#q3"
  get "results" => "pages#results"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
end

def about 
end

def test
end

def q1
end

def q2
end

def q3
end

def results
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Ace the PST</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Test", test_path%></li>

        <% if user_signed_in? %>
                  <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oneweekpst</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/header' %>
     <div class="container">


     	<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>
     	
          <%= yield %>
     </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>We are working on making acing the PST a cinch</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>Ace the Mckinsey Problem Solving Test, with just a few hours of prep.</h1>
     <% if user_signed_in? %>
          # do something
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>

app/views/pages/q1.html.erb
<h1>Q1</h1>
<p>Your first question is...based on what you know, what kind of food should Kosher Franks be serving?</p>


<%= radio_button_tag(:age, "hotdog") %>
<%= label_tag(:age_child, "They should serve hot dogs") %></br>
<%= radio_button_tag(:age, "burger") %>
<%= label_tag(:age_adult, "For sure they should serve burgers") %></br>
<%= radio_button_tag(:age, "vegetarian") %>
<%= label_tag(:age_vegetarian, "They should serve a range of vegetarian snacks") %></br>


</br></br><p>Go to the <%= link_to "next question", q2_path%></p>

app/views/pages/q2.html.erb
<h1>Q2</h1>
<p>Your second question is...well, also to be determined</p>

<p>Go to the<li><%= link_to "next question", q3_path%></li></p>

app/views/pages/q3.html.erb
<h1>Q3</h1>
<p>Your final question is at hand. Now on to the chance to see how you did.</p>

<p>Now go ahead and get your<%= link_to "results", results_path%></p>

app/views/pages/results.html.erb
<h1>Results</h1>
<p>And your final results are...</p>

app/views/pages/test.html.erb
<h1>Tests</h1>
<p>So this is a test version of...the test!</p>

<li><%= link_to "First question", q1_path%></li>
<li><%= link_to "Second question", q2_path%></li>
<li><%= link_to "Third question", q3_path%></li>